config/routes.rb
Rails.application.routes.draw do

get "tweets/" => "tweets#index"

get "tweets/new" => "tweets#new", as: :new_tweet

post "tweets/" => "tweets#create"

get "tweets/:id/edit" => "tweets#edit", as: :edit_tweet

patch "tweets/:id" => "tweets#update"

delete "tweets/:id" => "tweets#destroy"

get "tweets/:id" => "tweets#show", as: :tweet

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def index
    @tweets = Tweet.order('created_at DESC').all
  end

  def show
    @tweet = Tweet.find(params[:id])
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(params.require(:tweet).permit(:message, :user))

    if @tweet.save
      redirect_to tweets_path
    else
      render :new
    end
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    @tweet = Tweet.find(params[:id])

    if @tweet.update_attributes(params.require(:tweet).permit(:message, :user))
      redirect_to tweets_path
    else
      render :edit
    end
  end

  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy
    redirect_to tweets_path
  end








end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsTwitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tweets/edit.html.erb
<h1>Edit Tweet</h1>

<%= form_for @tweet do |f| %>

    <div>
        <%= f.label :message %>
        <%= f.text_field :message%>
    </div>

    <div>
        <%= f.label :user %>
        <%= f.text_field :user %>
    </div>

    <p><%= f.submit "Submit changes" %></p>

<% end %>

<p><%= link_to "Back to main tweets page", tweets_path %></p>

app/views/tweets/index.html.erb
<h1>Welcome to Chitter! Here's what's trending right now!</h1>

<p><%= link_to 'Got something worth sharing?', new_tweet_path %></p>

<ul class="tweet">
    <% @tweets.each do |tweet| %>
        <li>
            <p>@<%= tweet.user %> says:</p>
            <p></p>
            <p><strong> <%= tweet.message %> </strong></p>
            <p><%= link_to "Show", tweet %> <%= link_to "Edit", edit_tweet_path(tweet) %> <%= link_to 'Delete', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></p>
        </li>
    <% end %>
</ul>

app/views/tweets/new.html.erb
<h1>Write a new TWEET!!!!!</h1>

<%= form_for @tweet do |f| %>

  <div>
    <%= f.label :message%>
    <%= f.text_field :message, :maxlength => 100, :size => 50 %>
  </div>

  <div>
    <%= f.label :user%>
    <%= f.text_field :user%>
  </div>


<p><%= f.submit "Tweet that elloquent knowledge!" %></p>

<% end %>

<p><%= link_to "Show me some new tweets!", tweets_path %></p>

app/views/tweets/show.html.erb
<h1> Up close and personal with your tweet! </h1>

<ul class="tweet">
  <li>
    <p><strong><%= @tweet.message %></strong></p>
    <p>posted by @<%= @tweet.user %></p>
  </li>
</ul>


<%= link_to "Make a mistake? Edit your tweet!", edit_tweet_path %>

<p><%= link_to "I'm full of regret!! Delete!", tweet_path, method: :delete, data: { confirm: "Are you sure you want to delete this terrible tweet?"} %></p>

<p><%= link_to "Show me the newest tweets!!!", tweets_path %></p>